TARGET = Raptor.elf

CFLAGS   += -Wall -O2 -D__DC__ -DSDL12
CPPFLAGS += -Wall -O2 -D__DC__ -DSDL12 -fno-rtti -fno-exceptions -std=gnu++11

# Source and include directories
SRC_DIRS := src
INC_DIRS := src include/textscreen/include include/TimGM6mb include/TinySoundFont

# Find all source files in the SRC_DIRS
SRC_FILES := $(foreach dir,$(SRC_DIRS),$(wildcard $(dir)/*.c $(dir)/*.cc $(dir)/*.cpp $(dir)/*.m $(dir)/*.mm $(dir)/*.s $(dir)/*.S))

# Convert sources to object files
OBJS := $(patsubst %.c,%.o,$(patsubst %.cc,%.o,$(patsubst %.cpp,%.o,$(patsubst %.m,%.o,$(patsubst %.mm,%.o,$(patsubst %.s,%.o,$(patsubst %.S,%.o,$(SRC_FILES))))))))

# --- Romdisk support ---
KOS_ROMDISK_DIR = romfs
KOS_ROMDISK     = romdisk.o

# Add include flags
CPPFLAGS += $(foreach dir,$(INC_DIRS),-I$(dir))

all: rm-elf $(TARGET)

ifndef KOS_DEPDIR

%.o: %.c
	$(KOS_BASE)/utils/build_wrappers/kos-cc $(CFLAGS) $(CPPFLAGS) -c $< -o $@

%.o: %.cc
	$(KOS_BASE)/utils/build_wrappers/kos-c++ $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

%.o: %.cpp
	$(KOS_BASE)/utils/build_wrappers/kos-c++ $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

%.o: %.m
	$(KOS_BASE)/utils/build_wrappers/kos-cc $(CFLAGS) $(CPPFLAGS) -c $< -o $@

%.o: %.mm
	$(KOS_BASE)/utils/build_wrappers/kos-c++ $(CFLAGS) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

else

%.o: %.c
	$(KOS_BASE)/utils/build_wrappers/kos-cc -c $< -o $@ $(CXXFLAGS) $(CPPFLAGS) -MD -MF $(KOS_DEPDIR)/$(patsubst %.c,%.md,$(subst /,__,$(subst ..,,$<)))

%.o: %.cc
	$(KOS_BASE)/utils/build_wrappers/kos-c++ -c $< -o $@ $(CXXFLAGS) $(CPPFLAGS) -MD -MF $(KOS_DEPDIR)/$(patsubst %.cc,%.md,$(subst /,__,$(subst ..,,$<)))

%.o: %.cpp
	$(KOS_BASE)/utils/build_wrappers/kos-c++ -c $< -o $@ $(CXXFLAGS) $(CPPFLAGS) -MD -MF $(KOS_DEPDIR)/$(patsubst %.cpp,%.md,$(subst /,__,$(subst ..,,$<)))

%.o: %.m
	$(KOS_BASE)/utils/build_wrappers/kos-cc -c $< -o $@ $(CXXFLAGS) $(CPPFLAGS) -MD -MF $(KOS_DEPDIR)/$(patsubst %.m,%.md,$(subst /,__,$(subst ..,,$<)))

%.o: %.mm
	$(KOS_BASE)/utils/build_wrappers/kos-c++ -c $< -o $@ $(CXXFLAGS) $(CPPFLAGS) -MD -MF $(KOS_DEPDIR)/$(patsubst %.mm,%.md,$(subst /,__,$(subst ..,,$<)))

-include $(wildcard $(KOS_DEPDIR)/*.md)

endif

%.o: %.s
	$(KOS_BASE)//utils/build_wrappers/kos-as $< -o $@

%.o: %.S
	$(KOS_BASE)//utils/build_wrappers/kos-cc -c $< -o $@

%.bin: %.elf
	$(KOS_BASE)//utils/build_wrappers/kos-objcopy -O binary $< $@

# Romdisk rule
romdisk.img:
	genromfs -f romdisk.img -d $(KOS_ROMDISK_DIR) -v

romdisk.o: romdisk.img
	$(KOS_BASE)/utils/bin2o/bin2o romdisk.img romdisk $(KOS_ROMDISK)

# Link target with romdisk
$(TARGET): $(OBJS) $(KOS_ROMDISK)
	$(KOS_BASE)/utils/build_wrappers/kos-c++ -o $(TARGET) $(OBJS) $(KOS_ROMDISK) -lSDL -lkosfat

clean:
	-rm -f $(OBJS) $(TARGET) romdisk.img romdisk.o

rm-elf:
	-rm -f $(TARGET)

run: $(TARGET)
	$(KOS_LOADER) $(TARGET)

dist: $(TARGET)
	-rm -f $(OBJS)
	$(KOS_STRIP) $(TARGET)
